openapi: 3.0.0
info:
  title: Auctionable Change
  description: Backend API for the Auctionable Change mobile application.
                Created by Turing School of Software and Design students
                Stephanie Friend, Kevin McGrevey, Andrew Reid.
  version: 1.0.0
  authors: Stephanie Friend, Kevin McGrevey, Andrew Reid
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://auctionable-change-api.herokuapp.com
    description: Main (production) server
  - url: http://127.0.0.1:5000
    description: Local (development) server
tags:
  - name: Items
    description: Endpoints for Item CRUD
  - name: Bids
    description: Endpoints for Bid CRUD
  - name: Charities
    description: Endpoints for querying Charity Navigator
paths:
  /items:
    get:
      summary: Returns a list of available items.
      tags:
        - Items
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'

        '400':
          description: Bad Request
    post:
      summary: Creates a new item.
      tags:
        - Items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '400':
          description: Bad Request
  /items/{item_id}:
    get:
      summary: Returns a selected item.
      parameters:
        - in: path
          name: item_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the item to get
      tags:
        - Items
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'

        '404':
          description: Item not found
    put:
      summary: Updates a selected item.
      parameters:
        - in: path
          name: item_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the item to update
      tags:
        - Items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemRequest'
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'

        '404':
          description: Item not found
    delete:
      summary: Removes an item.
      parameters:
        - in: path
          name: item_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the item to delete
      tags:
        - Items
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Item not found
  /bids:
      get:
        summary: Returns a list of available bids.
        tags:
          - Bids
        responses:
          '200':    # status code
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Bid'

          '400':
            description: Bad Request
      post:
        summary: Creates a new bid.
        tags:
          - Bids
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BidRequest'
        responses:
          '200':
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Bid'
          '400':
            description: Bad Request
  /bids/{bid_id}:
    get:
      summary: Returns a selected bids.
      parameters:
        - in: path
          name: bid_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the bid to get
      tags:
        - Bids
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bid'

        '404':
          description: Bid not found
    put:
      summary: Updates a selected bids.
      parameters:
        - in: path
          name: bid_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the bid to update
      tags:
        - Bids
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BidRequest'
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bid'

        '404':
          description: Bid not found
    delete:
      summary: Removes an bid.
      parameters:
        - in: path
          name: bid_id
          schema:
            type: integer
          required: true
          description: Numeric ID of the bid to delete
      tags:
        - Bids
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bid'
        '404':
          description: Bid not found
  /charities:
    get:
      summary: Returns a list of rated charities from Charity Navigator.
      tags:
        - Charity
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Charity'

        '400':
          description: Bad Request
  /charities/{search_term}:
    get:
      summary: Searches for charities which match search term.
      parameters:
        - in: path
          name: search_term
          schema:
            type: string
          required: true
          description: String for which you wish to search
      tags:
        - Charity
      responses:
        '200':    # status code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Charity'

        '400':
          description: Bad Request
components:
  schemas:
    Item:
      allOf:
        - $ref: '#/components/schemas/ItemRequest'
        - type: object
          properties:
            id:
              type: integer
    ItemRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        donor:
          type: string
        donor_email:
          type: string
        status:
          type: string
        category:
          type: string
        charity:
          type: string
        charity_url:
          type: string
        charity_score:
          type: string
        charity_score_image:
          type: string
        image:
          type: string
    Bid:
      allOf:
        - $ref: '#/components/schemas/BidRequest'
        - type: object
          properties:
            id:
              type: integer
    BidRequest:
      type: object
      properties:
        bidder_name:
          type: string
        bidder_email:
          type: string
        amount:
          type: number
          format: float
        street_address:
          type: string
        city:
          type: string
        state:
          type: string
        zip_code:
          type: string
        receipt:
          type: string
        item_id:
          type: integer
    Charity:
      type: object
      properties:
        id:
          type: integer
        url:
          type: string
        name:
          type: string
        rating:
          type: integer
        rating_image:
          type: string
    # examples:
    #   itemExample:
    #     value:
    #       title: Photo
    #       description: Image of Johnny Cash
    #       price: 49.99
    #       donor: Andrew Reid
    #       donor_email: areid@example.com
    #       category: home
    #       charity: ProPublcia
    #       charity_url: https://www.charitynavigator.org/?bay=search.summary&orgid=13005&utm_source=DataAPI&utm_content=6bc9f3c8
    #       charity_score: 4
    #       charity_score_image: https://d20umu42aunjpx.cloudfront.net/_gfx_/icons/stars/4stars.png
    #       image: https://3w8dlo2orf8y3crtc22sslbh-wpengine.netdna-ssl.com/wp-content/uploads/2020/02/johnny-cash-1-.jpg
    #     summary: Sample item object
