language: python
python:
  - "3.6.7"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
virtualenv:
  system_site_packages: true
# command to run tests
# script:
#   - pytest
#
